import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { auth } from "../src/lib/firebase";
import Signup from "../src/components/Signup";
import Login from "../src/components/Login";

const Home = () => {
  const [user, setUser] = useState(null);
  const [selectedOption, setSelectedOption] = useState("login"); // "login" or "signup"
  const router = useRouter();

  useEffect(() => {
    const unsubscribe = auth.onAuthStateChanged((user) => {
      setUser(user);

      // Redirect to the game page after login
      if (user) {
        router.push("/game");
      }
    });

    // Cleanup the subscription when the component unmounts
    return () => unsubscribe();
  }, [router]);

  const handleLogin = () => {
    // You may want to perform additional actions on login
  };

  return (
    <div className="base">
    <div className='main'>
      {user ? (
        <div>
          <h1>Welcome, {user.email}!</h1>
        </div>
      ) : (
        <div className="main-land">
          <div className="selection-buttons">
            <button onClick={() => setSelectedOption("signup")}>Sign Up</button>
            <button onClick={() => setSelectedOption("login")}>Login</button>
          </div>

          {selectedOption === "login" && <Login onLogin={handleLogin} />}
          {selectedOption === "signup" && <Signup />}
        </div>
      )}
    </div>
    </div>
  );
};

export default Home;



// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
